"use client";
import { Download } from "lucide-react";
import { Button } from "../ui/button";

export default function DownloadSummaryButton({
	summaryText,
	title,
	fileName,
	createdAt,
}: {
	summaryText: string;
	title: string;
	fileName: string;
	createdAt: string;
}) {
	function handleDownload() {
		const summaryContent = `# ${title}\nGenerated Summary\nGenerated on: ${new Date(
			createdAt
		).toLocaleDateString()}\n\n${summaryText}\n\nOriginal File: ${fileName}\n\nGenerated by Sommaire ✨`;

		const blob = new Blob([summaryContent], { type: "text/plain" });
		const url = URL.createObjectURL(blob);
		const link = document.createElement("a");
		link.href = url;

		link.download = `Summary-${title.replace(/[^a-zA-Z0-9]/gi, "_")}.txt`;
		document.body.appendChild(link);
		link.click();

		document.body.removeChild(link);
		URL.revokeObjectURL(url);
	}
	return (
		<Button
			size="sm"
			className="h-8 px-3 text-rose-600 bg-rose-100 hover:text-rose-700 hover:bg-rose-50"
			onClick={handleDownload}
		>
			<Download className="h-4 w-4 mr-1" />
			Download Summary
		</Button>
	);
}
